# 환경별 경로 설정
paths:
  local:
    model: "model"
    data: "data"
    result: "result"
    log: "inference_ui/logs"
    temp_data: "preference_ui/temp_data"
  
  server:
    model: "/raid/sww/model"
    data: "/raid/sww/data"
    result: "/raid/sww/result"
    log: "/raid/sww/log"
    temp_data: "/raid/sww/temp_data"

# 기본 환경 (--local 없으면 server 사용)
default_environment: "server"
